### ISSUE TITLE
Rendering of <= and => for visualize.continuous when section = "tails"

### ISSUE THREAD

**Issue by louwerse** [coatless-rpkg/visualize#12]
Using R 4.2.2 in Windows, the following code does not render the `<=` and `=>` correctly. This only applies when `section = "tails"`. It seems that the code of `visualize.continuous` uses `bquote` to produce the subheading for this graph, but this does not work correctly anymore under R 4.2.2 (at least under Windows). Perhaps this is related to the move to UTF-8?   

``` r
visualize::visualize.norm(stat = c(-1, 1), section = "tails")
```

![](https://i.imgur.com/baVmUw8.png)

<sup>Created on 2022-11-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by coatless** [comment]
Whoops, sorry for not seeing this earlier. The short-gist is the direct unicode characters that were used are not portable on non-Unix alike systems. (Full details in #13). 

A new version of the package was sent over to CRAN that removed any unicode characters, e.g. `\u0...`, from the title area.
