### ISSUE TITLE
fomatting issue - text written over in title 

### ISSUE THREAD

**Issue by jricoiii** [coatless-rpkg/visualize#8]
![image](https://user-images.githubusercontent.com/50716185/65060136-30addd80-d92c-11e9-8388-5029b8285449.png)

The formatting is not working - I am unable to the proportion of the shaded area.  Text is being written on top of other text.

visualize.norm(110,100,10)

**Comment by jricoiii** [comment]
This is in Rmd.

When typed in console it works better.

**Comment by coatless** [comment]
@jricoiii I think this might be an issue with how `rmarkdown`/`knitr` handles the UTF-8 codes used for symbols on the plot. Thanks for the heads up.

**Comment by jricoiii** [comment]
any possible fixes to the formats

**Comment by coatless** [comment]
@jricoiii yup. Just give me a day or so. I just got back from a trip.

**Comment by coatless** [comment]
@jricoiii this is really a problem with the underlying RStudio inline renderer, c.f. rstudio/rstudio#5421.

Not sure how long the fix will take. I can't easily mitigate against it on my end.

**Comment by coatless** [comment]
I'm not sure if it was ever fixed as the RStudio issue ticket was marked as stale, c.f. https://github.com/rstudio/rstudio/issues/5421. So, I'm going to go ahead and close this out as this one is in RStudio's ballcourt.
